InsertionSort : InsertionSort.c
	gcc -g -std=c99 -Wall -Werror -o InsertionSort InsertionSort.c
BubbleSort : BubbleSort.c
	gcc -g -std=c99 -Wall -Werror -o BubbleSort BubbleSort.c
MergeSort : MergeSort.c
	gcc -g -std=c99 -Wall -Werror -o MergeSort MergeSort.c
